package fr.the__glacier.gworlds.Enums;

import org.bukkit.GameRule;

public enum Gamerules {
    ANNOUNCE_ADVANCEMENTS,
    BLOCK_EXPLOSION_DROP_DECAY,
    COMMAND_BLOCK_OUTPUT,
    COMMAND_MODIFICATION_BLOCK_LIMIT,
    DISABLE_ELYTRA_MOVEMENT_CHECK,
    // DISABLE_PLAYER_MOVEMENT_CHECK, -> since 1.21.3
    DISABLE_RAIDS,
    DO_DAYLIGHT_CYCLE,
    DO_ENTITY_DROPS,
    DO_FIRE_TICK,
    DO_IMMEDIATE_RESPAWN,
    DO_INSOMNIA,
    DO_LIMITED_CRAFTING,
    DO_MOB_LOOT,
    DO_MOB_SPAWNING,
    DO_PATROL_SPAWNING,
    DO_TILE_DROPS,
    DO_TRADER_SPAWNING,
    DO_VINES_SPREAD,
    DO_WARDEN_SPAWNING,
    DO_WEATHER_CYCLE,
    DROWNING_DAMAGE,
    ENDER_PEARLS_VANISH_ON_DEATH,
    FALL_DAMAGE,
    FIRE_DAMAGE,
    FORGIVE_DEAD_PLAYERS,
    FREEZE_DAMAGE,
    GLOBAL_SOUND_EVENTS,
    KEEP_INVENTORY,
    LAVA_SOURCE_CONVERSION,
    LOG_ADMIN_COMMANDS,
    MAX_COMMAND_CHAIN_LENGTH,
    MAX_COMMAND_FORK_COUNT,
    MAX_ENTITY_CRAMMING,
    // MINECART_MAX_SPEED, -> since 1.21.3
    MOB_EXPLOSION_DROP_DECAY,
    MOB_GRIEFING,
    NATURAL_REGENERATION,
    PLAYERS_NETHER_PORTAL_CREATIVE_DELAY,
    PLAYERS_NETHER_PORTAL_DEFAULT_DELAY,
    PLAYERS_SLEEPING_PERCENTAGE,
    PROJECTILES_CAN_BREAK_BLOCKS,
    RANDOM_TICK_SPEED,
    REDUCED_DEBUG_INFO,
    SEND_COMMAND_FEEDBACK,
    SHOW_DEATH_MESSAGES,
    SNOW_ACCUMULATION_HEIGHT,
    SPAWN_CHUNK_RADIUS,
    SPAWN_RADIUS,
    SPECTATORS_GENERATE_CHUNKS,
    TNT_EXPLOSION_DROP_DECAY,
    UNIVERSAL_ANGER,
    WATER_SOURCE_CONVERSION;

    public GameRule<?> getGamerule(){
        return switch (this){
            case ANNOUNCE_ADVANCEMENTS -> GameRule.ANNOUNCE_ADVANCEMENTS;
            case DO_INSOMNIA -> GameRule.DO_INSOMNIA;
            case DO_MOB_LOOT -> GameRule.DO_MOB_LOOT;
            case FALL_DAMAGE -> GameRule.FALL_DAMAGE;
            case FIRE_DAMAGE -> GameRule.FIRE_DAMAGE;
            case DO_FIRE_TICK -> GameRule.DO_FIRE_TICK;
            case MOB_GRIEFING -> GameRule.MOB_GRIEFING;
            case SPAWN_RADIUS -> GameRule.SPAWN_RADIUS;
            case DISABLE_RAIDS -> GameRule.DISABLE_RAIDS;
            case DO_TILE_DROPS -> GameRule.DO_TILE_DROPS;
            case FREEZE_DAMAGE -> GameRule.FREEZE_DAMAGE;
            case KEEP_INVENTORY -> GameRule.KEEP_INVENTORY;
            case DO_ENTITY_DROPS -> GameRule.DO_ENTITY_DROPS;
            case DO_MOB_SPAWNING -> GameRule.DO_MOB_SPAWNING;
            case DO_VINES_SPREAD -> GameRule.DO_VINES_SPREAD;
            case DROWNING_DAMAGE -> GameRule.DROWNING_DAMAGE;
            case UNIVERSAL_ANGER -> GameRule.UNIVERSAL_ANGER;
            case DO_WEATHER_CYCLE -> GameRule.DO_WEATHER_CYCLE;
            case DO_DAYLIGHT_CYCLE -> GameRule.DO_DAYLIGHT_CYCLE;
            case RANDOM_TICK_SPEED -> GameRule.RANDOM_TICK_SPEED;
            case DO_PATROL_SPAWNING -> GameRule.DO_PATROL_SPAWNING;
            case DO_TRADER_SPAWNING -> GameRule.DO_TRADER_SPAWNING;
            case DO_WARDEN_SPAWNING -> GameRule.DO_WARDEN_SPAWNING;
            case LOG_ADMIN_COMMANDS -> GameRule.LOG_ADMIN_COMMANDS;
            case REDUCED_DEBUG_INFO -> GameRule.REDUCED_DEBUG_INFO;
            case SPAWN_CHUNK_RADIUS -> GameRule.SPAWN_CHUNK_RADIUS;
            case DO_LIMITED_CRAFTING -> GameRule.DO_LIMITED_CRAFTING;
            case GLOBAL_SOUND_EVENTS -> GameRule.GLOBAL_SOUND_EVENTS;
            case MAX_ENTITY_CRAMMING -> GameRule.MAX_ENTITY_CRAMMING;
            case SHOW_DEATH_MESSAGES -> GameRule.SHOW_DEATH_MESSAGES;
            case COMMAND_BLOCK_OUTPUT -> GameRule.COMMAND_BLOCK_OUTPUT;
            case DO_IMMEDIATE_RESPAWN -> GameRule.DO_IMMEDIATE_RESPAWN;
            case FORGIVE_DEAD_PLAYERS -> GameRule.FORGIVE_DEAD_PLAYERS;
            case NATURAL_REGENERATION -> GameRule.NATURAL_REGENERATION;
            case SEND_COMMAND_FEEDBACK -> GameRule.SEND_COMMAND_FEEDBACK;
            case LAVA_SOURCE_CONVERSION -> GameRule.LAVA_SOURCE_CONVERSION;
            case MAX_COMMAND_FORK_COUNT -> GameRule.MAX_COMMAND_FORK_COUNT;
            case WATER_SOURCE_CONVERSION -> GameRule.WATER_SOURCE_CONVERSION;
            case MAX_COMMAND_CHAIN_LENGTH -> GameRule.MAX_COMMAND_CHAIN_LENGTH;
            case MOB_EXPLOSION_DROP_DECAY -> GameRule.MOB_EXPLOSION_DROP_DECAY;
            case SNOW_ACCUMULATION_HEIGHT -> GameRule.SNOW_ACCUMULATION_HEIGHT;
            case TNT_EXPLOSION_DROP_DECAY -> GameRule.TNT_EXPLOSION_DROP_DECAY;
            case BLOCK_EXPLOSION_DROP_DECAY -> GameRule.BLOCK_EXPLOSION_DROP_DECAY;
            case SPECTATORS_GENERATE_CHUNKS -> GameRule.SPECTATORS_GENERATE_CHUNKS;
            case PLAYERS_SLEEPING_PERCENTAGE -> GameRule.PLAYERS_SLEEPING_PERCENTAGE;
            case ENDER_PEARLS_VANISH_ON_DEATH -> GameRule.ENDER_PEARLS_VANISH_ON_DEATH;
            case PROJECTILES_CAN_BREAK_BLOCKS -> GameRule.PROJECTILES_CAN_BREAK_BLOCKS;
            case DISABLE_ELYTRA_MOVEMENT_CHECK -> GameRule.DISABLE_ELYTRA_MOVEMENT_CHECK;
            case COMMAND_MODIFICATION_BLOCK_LIMIT -> GameRule.COMMAND_MODIFICATION_BLOCK_LIMIT;
            case PLAYERS_NETHER_PORTAL_DEFAULT_DELAY -> GameRule.PLAYERS_NETHER_PORTAL_DEFAULT_DELAY;
            case PLAYERS_NETHER_PORTAL_CREATIVE_DELAY -> GameRule.PLAYERS_NETHER_PORTAL_CREATIVE_DELAY;
            default -> null;
        };
    }
}
